<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CliInvoke" Version="2.11.0" />
    <PackageVersion Include="CliInvoke.Core" Version="2.11.0" />
    <PackageVersion Include="CliInvoke.Extensions" Version="2.11.0" />
    <PackageVersion Include="DotMake.CommandLine" Version="3.7.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Terminal.Gui" Version="2.4.17" />
    <PackageVersion Include="Tomlyn" Version="2.10.1" />
    <PackageVersion Include="TUnit" Version="1.66.16" />
  </ItemGroup>
</Project>