//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoAuthor.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoAuthor.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add co-author {0} to config file &apos;{1}&apos;.
        /// </summary>
        internal static string Commands_Authors_Add_Failed {
            get {
                return ResourceManager.GetString("Commands.Authors.Add.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoAuthor &apos;{0}&apos; was successfully added to &apos;{1}&apos; config file..
        /// </summary>
        internal static string Commands_Authors_Add_Successful {
            get {
                return ResourceManager.GetString("Commands.Authors.Add.Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform commit with co-author/assist message: &apos;{0}&apos;.
        /// </summary>
        internal static string Commands_Commit_Failed_Generic {
            get {
                return ResourceManager.GetString("Commands.Commit.Failed.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details: .
        /// </summary>
        internal static string Commands_Exceptions_Details {
            get {
                return ResourceManager.GetString("Commands.Exceptions.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to produce commit message with co-author/assist message: &apos;{0}&apos;.
        /// </summary>
        internal static string Commands_Message_Failed {
            get {
                return ResourceManager.GetString("Commands.Message.Failed", resourceCulture);
            }
        }
    }
}
