//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoAttribution.Cli.Localizations {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoAttribution.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add co-author &apos;{0}&apos; to config file &apos;{1}&apos;.
        /// </summary>
        internal static string Commands_Authors_Add_Failed {
            get {
                return ResourceManager.GetString("Commands.Authors.Add.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoAuthor &apos;{0}&apos; was successfully added to &apos;{1}&apos; config file..
        /// </summary>
        internal static string Commands_Authors_Add_Successful {
            get {
                return ResourceManager.GetString("Commands.Authors.Add.Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove co-authors: &apos;{0}&apos;.
        /// </summary>
        internal static string Commands_Authors_Remove_Failed {
            get {
                return ResourceManager.GetString("Commands.Authors.Remove.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform commit with co-author/assist message: &apos;{0}&apos;.
        /// </summary>
        internal static string Commands_Commit_Failed_Generic {
            get {
                return ResourceManager.GetString("Commands.Commit.Failed.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error whilst getting a config value associated with key &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Commands_Config_EncounteredError_GetValue {
            get {
                return ResourceManager.GetString("Commands.Config.EncounteredError.GetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error whilst setting a config value associated with key &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Commands_Config_EncounteredError_SetValue {
            get {
                return ResourceManager.GetString("Commands.Config.EncounteredError.SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Key &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string Commands_Config_KeyNotValid {
            get {
                return ResourceManager.GetString("Commands.Config.KeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details: .
        /// </summary>
        internal static string Commands_Exceptions_Details {
            get {
                return ResourceManager.GetString("Commands.Exceptions.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file created at: {0}.
        /// </summary>
        internal static string Commands_Init_ConfigFileCreated {
            get {
                return ResourceManager.GetString("Commands.Init.ConfigFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t initialise the config file.
        /// </summary>
        internal static string Commands_Init_Failed {
            get {
                return ResourceManager.GetString("Commands.Init.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to produce commit message with co-author/assist message: &apos;{0}&apos;.
        /// </summary>
        internal static string Commands_Message_Failed {
            get {
                return ResourceManager.GetString("Commands.Message.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file path &apos;{0}&apos; is not a valid TOML configuration file.
        /// </summary>
        internal static string Exceptions_Arguments_InvalidConfigFileConfiguration {
            get {
                return ResourceManager.GetString("Exceptions.Arguments.InvalidConfigFileConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file does not specify the AUTHORS toml file to use, and no local AUTHORS toml file exists in the current directory..
        /// </summary>
        internal static string Exceptions_FileNotFound_AuthorsFile {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound.AuthorsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the config file at path &apos;{0}&apos; to be used..
        /// </summary>
        internal static string Exceptions_FileNotFound_ConfigFile {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound.ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the file path for the Configuration to be created..
        /// </summary>
        internal static string Exceptions_FileNotFound_ConfigFile_ToCreate {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound.ConfigFile.ToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined coauthor.
        /// </summary>
        internal static string Labels_Authors_Undefined {
            get {
                return ResourceManager.GetString("Labels.Authors.Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Agent.
        /// </summary>
        internal static string Labels_AuthorTypes_Values_Agent {
            get {
                return ResourceManager.GetString("Labels.AuthorTypes.Values.Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other AI mode.
        /// </summary>
        internal static string Labels_AuthorTypes_Values_AI_Other {
            get {
                return ResourceManager.GetString("Labels.AuthorTypes.Values.AI_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string Labels_AuthorTypes_Values_Human {
            get {
                return ResourceManager.GetString("Labels.AuthorTypes.Values.Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Labels_Buttons_Cancel {
            get {
                return ResourceManager.GetString("Labels.Buttons.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Labels_Buttons_Okay {
            get {
                return ResourceManager.GetString("Labels.Buttons.Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Author.
        /// </summary>
        internal static string Labels_Buttons_SaveAuthor {
            get {
                return ResourceManager.GetString("Labels.Buttons.SaveAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrbutor Type.
        /// </summary>
        internal static string Labels_Input_ContributorType {
            get {
                return ResourceManager.GetString("Labels.Input.ContributorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Labels_Input_Email {
            get {
                return ResourceManager.GetString("Labels.Input.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Labels_Input_Name {
            get {
                return ResourceManager.GetString("Labels.Input.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add CoAuthor.
        /// </summary>
        internal static string Labels_MessageBoxes_Authors_Add_Failed {
            get {
                return ResourceManager.GetString("Labels.MessageBoxes.Authors.Add.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No per-host identity block is configured for host &apos;{0}&apos;..
        /// </summary>
        internal static string Diagnostics_MissingHostBlock_Header {
            get {
                return ResourceManager.GetString("Diagnostics.MissingHostBlock.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor: {0}.
        /// </summary>
        internal static string Diagnostics_MissingHostBlock_Contributor {
            get {
                return ResourceManager.GetString("Diagnostics.MissingHostBlock.Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry file: {0}.
        /// </summary>
        internal static string Diagnostics_MissingHostBlock_Registry {
            get {
                return ResourceManager.GetString("Diagnostics.MissingHostBlock.Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the following block to &apos;{0}&apos;:.
        /// </summary>
        internal static string Diagnostics_MissingHostBlock_Snippet {
            get {
                return ResourceManager.GetString("Diagnostics.MissingHostBlock.Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Diagnostics_MissingHostBlock_SnippetBody {
            get {
                return ResourceManager.GetString("Diagnostics.MissingHostBlock.SnippetBody", resourceCulture);
            }
        }
    }
}
