# configuration file for dotnet-releaser
[msbuild]
project = "CoAttribution.Cli/CoAttribution.Cli.csproj"
[github]
user = "alastairlundy"
repo = "CoAttribution"
[changelog]
publish = false
[nuget]
publish = true
