<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>co-attr</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>CoAttribution</Title>
        <Authors>Alastair Lundy</Authors>
        <Copyright>Copyright (c) Alastair Lundy 2026</Copyright>
        <RepositoryUrl>https://github.com/alastairlundy/CoAttribution</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>attribution, assisted-by, coauthored-by</PackageTags>
        <IsPackable>true</IsPackable>
        <IsTrimmable>true</IsTrimmable>
        <IsAoTCompatible>true</IsAoTCompatible>
        <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <RootNamespace>CoAttribution.Cli</RootNamespace>
        <PackageId>CoAttribution</PackageId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CliInvoke.Extensions" />
      <PackageReference Include="DotMake.CommandLine" />
      <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Terminal.Gui" />
      <PackageReference Include="Tomlyn" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="DEFAULT_AUTHORS.toml" LogicalName="DEFAULT_AUTHORS.toml" />
      <None Update="DEFAULT_AUTHORS.toml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Localizations\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Localizations\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoAttribution.Lib\CoAttribution.Lib.csproj" />
    </ItemGroup>


</Project>
